name = "excalidraw"
main = "worker.ts"
compatibility_date = "2024-01-01"

[assets]
directory = "build"
binding = "ASSETS"

[[kv_namespaces]]
binding = "EXCALIDRAW_KV"
id = "aaf653e38de14c3f8285f1c8a4ee5cb7"
preview_id = "aaf653e38de14c3f8285f1c8a4ee5cb7"
